### ISSUE TITLE
Request: Platform Icon Overlay Theme

### ISSUE THREAD

**Issue by Rumik** [suchmememanyskill/SDH-CssLoader#104]
Hi there!

Not sure if this is the right post to request this. I think it would be amazing if some CSS wizard made it possible to specify a platform icon for each game, much like the theme that shows a "installed" icon in the corner of the game grid artwork. Not sure how possible that is, but I think it'd be a great idea.

Use case: I have locally installed PC games, but I also have emulated Switch games too. And I use PlayStation Remote Play and Xbox Remote Play/Game Pass. It would be amazing to be able to include icons for each of these in the corner of the game grid artwork.

Thanks for reading!

**Comment by suchmememanyskill** [comment]
This isn't possible as a css theme; css is just styling, not adding data.

This is also not the right place to request themes
