### ISSUE TITLE
Inject HTML Support possible?

### ISSUE THREAD

**Issue by joamjoamjoam** [suchmememanyskill/SDH-CssLoader#12]
I'm looking to inject HowLongToBeat data into a sub div on the game page. Is there any plans to support something like this? Inject JavaScript Support? 

I'm looking for something similar in functionality to the Crankshaft loaders ProtonDB plugin but I need something that is loadable by Decky Loader.

**Comment by suchmememanyskill** [comment]
Sir this is a theme loader. Not a plugin loader. No i don't want to support injecting js

**Comment by joamjoamjoam** [comment]
Understood. Since you already injected your CSS using javascript (inject_css_into_tab) I thought it may have been possible to extend your themes to include more things. I understand if you want to keep this as purely a CSS retheme. Since the actual injection is done by DeckyLoader ill probably look into creating my own plugin since the JS injection capabilities I need are there. 

Thanks for the quick reply and for this plugin, I've been working on some themes and will be submitting to the theme DB soon.
