### ISSUE TITLE
No themes listed under app? Only 'Reload Themes'

### ISSUE THREAD

**Issue by xFaultx** [suchmememanyskill/SDH-CssLoader#2]
So I've tried both installing through the plugin loader and manually copying and pasting the github files in desk mode. I've changed the permission on all the folders to view and edit on desktop mode, but nothing has changed. Is there some separate permission that I need to provide, either to the plugin or plugin loader so it can see the folders? They are structured the same way as the github is.

**Comment by suchmememanyskill** [comment]
Resolved in discord
