### ISSUE TITLE
Locally host images for themes

### ISSUE THREAD

**Issue by joamjoamjoam** [suchmememanyskill/SDH-CssLoader#20]
As a theme user id like to be able to use themes with images without internet and witbout the performance penalty of encoding the image as base64. 

Since the deck is used in places without internet it would be nice if the plugin could locally host a themes assets so they are available when internet is not. 

Maybe each theme could have an assets folder that gets hosted and can be accessed at localhost/themename/assets. 

Adding as an issue as per the conversation with @suchmememanyskill

**Comment by EMERALD0874** [comment]
@suchmememanyskill plans to investigate this when he has time due to recent developments discovered in the Audio Loader.
