### ISSUE TITLE
Add color patch type

### ISSUE THREAD

**Issue by EMERALD0874** [suchmememanyskill/SDH-CssLoader#21]
Add a patch type for a custom color. This will allow a theme creator to set a root variable as an HSL color defined by the user using a color picker. The most recent development image is shown below.
![image](https://user-images.githubusercontent.com/11338953/184755713-594644fd-b8fb-41fb-af7f-70cf0e822ce1.png)

**Comment by beebls** [comment]
The entire front-end for this is done, we're just workin on the backend implementation

**Comment by joamjoamjoam** [comment]
A color Opacity slider would be nice to have to support translucent colors for things like keyboard keys, focusable panels over images etc. 

Talked to beebles and he said he might toy around with adding it but with all the decky loader broken webpack stuff going on i figured i should ink it down so it doesnt get lost.
