### ISSUE TITLE
Cannot install themes

### ISSUE THREAD

**Issue by rpath16** [suchmememanyskill/SDH-CssLoader#26]
As the title suggests, I am unable to install any themes. Every other plug-in works perfectly but for some reason, trying to install themes from css loader doesn't work. Clicking on "install" does nothing. I don't see any error. I have re-imaged my Deck 3-4 times now and the result is the same.

**Comment by suchmememanyskill** [comment]
Is this your reddit account/post https://www.reddit.com/r/SteamDeck/comments/wojll1/-/ilgmeut

If so: i just replied to it. Nothing is wrong from our side. There seems to be issues with your networking setup

**Comment by rpath16** [comment]
Thank you so much! Please go ahead and close this ticket. No idea why my network settings got borked but that's for another time.
