### ISSUE TITLE
Patching the built-in browser

### ISSUE THREAD

**Issue by aph3rson** [suchmememanyskill/SDH-CssLoader#29]
Less of a bug, more of a question. 

The Steam Deck's built-in browser (e.g. for the store, or other pages on the Steam website) and the stock deck theme are designed to match pretty-uniformly. However, for users of custom CSS themes, this browser is unpatched.

As an example, here's me using EMERALD0874's Galactic theme and browsing a store page - note that the store page is entirely unthemed.
![20220914231134_1](https://user-images.githubusercontent.com/838916/190328589-39b6cbaa-7399-4dad-b7ac-535a0ca95765.jpg)

Therefore, two questions:
- Can CSS be injected into this DOM via the same mechanism as the UI? Or are there two different mechanisms for doing so?
- Would the same CSS for the UI work for the browser? Looking at some of the CSS, it doesn't look like it'd be Deck-specific, but I'm unsure

**Comment by suchmememanyskill** [comment]
It's been a while but at some point i tried injecting into the 'great on deck' tab, and it worked fine. The only issue is that you need to rely on the automatic reinjection for the theme to be injected, which is slow (runs every 3s)

I am unsure if you can theme the steam ui with the same css as the webpage. The deck ui's class names are quite unique

**Comment by suchmememanyskill** [comment]
Stale issue. If this is actually an issue please re-open

**Comment by aph3rson** [comment]
@suchmememanyskill: this is/was a feature request, not a stale issue. The feature doesn't exist.

Can you re-open this, please?

**Comment by suchmememanyskill** [comment]
but the feature does exist?

**Comment by aph3rson** [comment]
Okay, I'll give that a shot, then.

Thanks!

**Comment by suchmememanyskill** [comment]
[Test5.zip](https://github.com/suchmememanyskill/SDH-CssLoader/files/9905924/Test5.zip)
![image](https://user-images.githubusercontent.com/38142618/199137633-e4cc133e-bcba-430c-9594-62038ddeaf88.png)
Turns the top bar black
