### ISSUE TITLE
Themes Not working after decky update

### ISSUE THREAD

**Issue by powl999** [suchmememanyskill/SDH-CssLoader#33]
After an Update by decky all themes are still in the quick Access Menu but do Not work

**Comment by suchmememanyskill** [comment]
Decky issue probably, not a me issue. I'm already discussing with them how to fix it

**Comment by powl999** [comment]
> 

Thanks die the quick reply and for the great Plugin that you hast created

**Comment by suchmememanyskill** [comment]
Fixed with a decky update
