### ISSUE TITLE
[Feature Request] Add option to disable themes when external monitor is connected

### ISSUE THREAD

**Issue by KrisCris** [suchmememanyskill/SDH-CssLoader#36]
I just got my steam deck dock and realized that when it connects to an external display, nearly all the themes are messed up - So, I am looking for a way to temporarily disable all the 3rd party CSSs.

**Comment by suchmememanyskill** [comment]
Ask the themes authors to include a media clause to disable the theme on bigger displays or make it responsive: i don't feel like it's our job to disable all themes like that

**Comment by KrisCris** [comment]
Perfect, I manually added the media query to those themes lol.

```css
@media only screen and (max-width: 1280px) {
 ...
}
```
