### ISSUE TITLE
cssloader failed to initialize

### ISSUE THREAD

**Issue by Rickroll10000** [suchmememanyskill/SDH-CssLoader#44]
I went to grab some themes and it wasn't connecting to the database for themes and when i exited it said the plugin failed to initialize it seemed to also affect Audio Loader whatever it was

**Comment by suchmememanyskill** [comment]
Please be more specific in what happens. What are the steps to reproduce? What do you see? What steamos and decky version do you run?

Note, on decky stable and steamos stable right now, cssloader is broken due to decky. I'm awaiting a fix but cannot do anything about it

**Comment by Rickroll10000** [comment]
Ah I'm on the stable releases for both decky and SteamOS but yeah you kind of just laid what was happening yourself lol so is there a way to downgrade decky to the point before it broke the loaders without sudo I'm not particularly fancying have to reimage my steam deck just yet since my sudo passwd seems to have to reset itself?

**Comment by suchmememanyskill** [comment]
You can either
- downgrade cssloader to v1.3.0
- upgrade to decky pre-release and steamos beta/preview

**Comment by StephenCPrice** [comment]
Had this issue, downgraded to 1.3.0, restarted steam deck and manage themese worked so I sucessfully changed back to 1.3.1 without it breaking again. I suspect starting the steam deck is what fixed it. Btw this was immediately after installing both decky and css loader.

**Comment by suchmememanyskill** [comment]
Issue is now irrelelvant with the release of cssloader v1.3.2
