### ISSUE TITLE
BUG - Themes not working on latest SteamOS Preview

### ISSUE THREAD

**Issue by maddogspeighty** [suchmememanyskill/SDH-CssLoader#52]
My deck has just updated to the latest preview build and I noticed any themes I had set through css loader had disabled.

Enabling any that effect the home screen aren't working at all, some that affect the colour of the QAM and so on seem to work.

I'm on the latest pre release of decky loader.

I've tried reloading css loader and restarting my deck but it's still the same.

**Comment by maddogspeighty** [comment]
> Known issue. The SP tab got renamed. I'm currently working on a fix

Apologies, I did have a look but couldn't see anything.

**Comment by suchmememanyskill** [comment]
Fix @ dcdc5ed
