### ISSUE TITLE
Expand/Collapsible Style Settings

### ISSUE THREAD

**Issue by CarJem** [suchmememanyskill/SDH-CssLoader#54]
when you have a lot of styles, with a lot of options, You might find that it be tedious to navigate... I propose that style settings can be collapsed by default and then manually expanded. alternatively put the settings on a secondary page

**Comment by suchmememanyskill** [comment]
This is already planned i think

We plan to make a 'main' view, where you can pin specific themes, and within the main view there's a button to go to a secondary view which contains all views.

This is as far as i know what's planned but @beebls probably can tell you more

**Comment by beebls** [comment]
Suchmeme got it right on.

What we're going to do is allow you to "pin" themes to the QAM menu, you can pin as many as you want, but that means that they will show up there exactly as they do right now, and the rest will go into an overflow menu which is fullscreen and collapsible, allowing for much easier customization & access.

**Comment by beebls** [comment]
Closing as this has been added in 1.5.0
