### ISSUE TITLE
Latest SteamOS Beta translates the SP tab's name

### ISSUE THREAD

**Issue by dimitrij2k** [suchmememanyskill/SDH-CssLoader#57]
I tested the latest Beta of SteamOS and the 28.01. released beta breaked CSS Loader. No function at all.

Revert back to "stable" channel fixed CSS Loader.

**Comment by suchmememanyskill** [comment]
What language is your deck set to? I've gotten bug reports that some tabs have names that are translated

**Comment by dimitrij2k** [comment]
> What language is your deck set to? I've gotten reports that some tabs have names that are translated. Names are what cssloader uses to indentify tabs

German - but none of the Themes worked. The whole Plugin dont work.

**Comment by suchmememanyskill** [comment]
That's the issue i've gotten reports about then. The dev branch of cssloader has a fix in it

**Comment by beebls** [comment]
Closing as the issue is fixed in v1.5.0 and is soon to be released to decky

If you need a fix for the issue immediately, you can compile the plugin from here, or go to the decky-plugin-database PR and download the compiled file.
