### ISSUE TITLE
Custom css code

### ISSUE THREAD

**Issue by HahBikes** [suchmememanyskill/SDH-CssLoader#58]
Add the ability to directly inject custom css code snippets from the plugin itself

**Comment by suchmememanyskill** [comment]
You'd have to be more specific, If you mean:
- I want to write css in the deck ui itself: imo writing anything in there is a horrible ux experience and i don't even think it should be a thing
- I want to write css without learning the theme.json format: You can throw a css file named `theme.css` in a new folder in `~/homebrew/themes`, and it'll show up as a theme

**Comment by suchmememanyskill** [comment]
No response, will just assume you got what you needed
