### ISSUE TITLE
Change 'pin' icon to 'visible/invisible' icon

### ISSUE THREAD

**Issue by suchmememanyskill** [suchmememanyskill/SDH-CssLoader#64]

**Comment by beebls** [comment]
fixed in commit [d0d2fd9](https://github.com/suchmememanyskill/SDH-CssLoader/commit/d0d2fd96bb9b4e20a84a2e416c2f4d6e6285e274)

**Comment by beebls** [comment]
![image](https://user-images.githubusercontent.com/102569435/216205551-7f7c31ab-afa7-45e2-94ac-0b70a706ae42.png)
Image for reference

**Comment by beebls** [comment]
reopening until full release
