### ISSUE TITLE
Keyboard issues in Desktop mode

### ISSUE THREAD

**Issue by Tormak9970** [suchmememanyskill/SDH-CssLoader#67]
Since updating to CssLoader v1.5.0 my theme (SteamDeck U) which styles the keyboard is now working in desktop mode (with no changes), but I can't navigate the keyboard with the thumbstick. This could also be a Steam bug, I'm not sure

**Comment by suchmememanyskill** [comment]
Cannot consistently reproduce 
![image](https://user-images.githubusercontent.com/38142618/216647080-0e75c093-84c9-4191-80fb-c6414068dfb7.png)

**Comment by suchmememanyskill** [comment]
Note i got it to reproduce once, when i booted into desktop mode the first time. I'm also running review. Let me check

**Comment by suchmememanyskill** [comment]
Forgot to reply, it works fine for me on desktop with your theme

**Comment by Tormak9970** [comment]
> Forgot to reply, it works fine for me on desktop with your theme

Ight. Not a big issue for me, prob just steam acting up.
