### ISSUE TITLE
[Enhancement] Support for your Decky Loader fork

### ISSUE THREAD

**Issue by ShadowEO** [suchmememanyskill/SDH-CssLoader#69]
First off, Your decky loader fork works great on Windows. But the CSS loader calls some platform-specific code for Linux in css-utils.py and css-inject.py. Such as getting the user home path and the UID. I have encountered any additional platform specific code yet that throws exceptions in your Windows Decky Loader fork.

The home directory should be retrieved using pathlib and on Windows the EUID/UID should be ignored. Changing that made the CSS loader work great. I am having no problems with themes (though for some reason the store won't work properly, it seems to download the ZIP file and then fails to unzip it to the themes directory, so manual installation of the themes is required)

**Comment by suchmememanyskill** [comment]
Sir please look at the dev branch
