### ISSUE TITLE
Clear cache on theme refresh

### ISSUE THREAD

**Issue by ChrisAnd1998** [suchmememanyskill/SDH-CssLoader#70]
For easy editing I am loading the css file from url. It works but to see the changes the browser cache must be cleared and the Deck must be restarted.

**shared.css**
`@import url("https://chrisandriessen.nl/steamdeck/shared.css");`

**Comment by suchmememanyskill** [comment]
i don't see how that's our issue.

Also, are you not looking for something like this? https://docs.deckthemes.com/#/CSSLoader/Features?id=%f0%9f%a7%ad-file-watcher

**Comment by ChrisAnd1998** [comment]
@suchmememanyskill Thank you for your quick response. The issue is that the file from url in this case _https://chrisandriessen.nl/steamdeck/shared.css_ gets cached so the Css loader will not see any changes because it's cached by the Steam Deck. If Css loader could clear the Decks browser cache this should be fixed. I have added the WATCH file but that does not work as the shared.css file is not being changed.

The contents of that file will always be
`@import url("https://chrisandriessen.nl/steamdeck/shared.css");`

so it actually loads the contents of that online hosted css file _https://chrisandriessen.nl/steamdeck/shared.css_

```
.quickaccessmenu_QuickAccessMenu_V0cr-,.quickaccessmenu_Title_34nl5,.quickaccessmenu_Tab_1S76C {
    background: blue;
}

.quickaccessmenu_Title_34nl5 {
    box-shadow: none;
}

.gamepadhomerecentgames_RecentGamesHeader_35iRe {
    display:none!important;
}
```

**Comment by suchmememanyskill** [comment]
Again, i don't see how that's our issue. You're currently doing something i think is outside the scope of this project (cssloader loads css from local files, not remote files).

The watch feature allows you to remotely edit the local .css files via sftp or something, and they'll automatically get reloaded

**Comment by ChrisAnd1998** [comment]
@suchmememanyskill Thank you. I will try to find another solution.

**Comment by ChrisAnd1998** [comment]
@suchmememanyskill Currently have set it up with **sshfs** works like a charm! ;)
