### ISSUE TITLE
Theme changes stuck after Decky Loader reinstall

### ISSUE THREAD

**Issue by TheDenast** [suchmememanyskill/SDH-CssLoader#76]
Some OS update has removed Decky Loader for me, so I had to reinstall it. All of my plugins remained after previous install, but CSS Loader now thinks that all of the changes I made before the reinstall are the "default" look of the UI, making me practically stuck with all the changes. I can apply more changes on top, but flicking my current theme back and forth does nothing.

 Is there any way to restore the default CSS look?

**Comment by suchmememanyskill** [comment]
Restart steam or the device?

**Comment by TheDenast** [comment]
This worked! Sorry for issue spam
