### ISSUE TITLE
CSS Loader failed to Initialize

### ISSUE THREAD

**Issue by madhatpoet** [suchmememanyskill/SDH-CssLoader#78]
I just updated Steam OS to version 3.4.6 on the stable channel and CSS Loader is now displaying a message that it failed to initialize. It says to try restarting the steam deck, which I've tried a few times. I've also tried uninstalling and reinstalling CSS Loader. I should mention that I initally had issues with one other plugin "Audio Loader", but I have sense got that one working again by restarting the deck.

**Comment by suchmememanyskill** [comment]
Can you get the backend logs for me?

`journalctl -u plugin_loader -b0 > logs.txt` in konsole drops a file called logs.txt in the same folder as konsole is running. Please send that here

**Comment by suchmememanyskill** [comment]
Version on the store currently does not function due to CI issue's on decky's side. Please stand by

**Comment by unicornsandcandies** [comment]
> Version on the store currently does not function due to CI issue's on decky's side. Please stand by

Are there any clues to when will it work again? I can't see the related issue on decky github. I'm at the point where I honestly cannot live without CSS loader. I'll gladly send any info possible to help with this.

**Comment by suchmememanyskill** [comment]
You can download the previous version (1.5.2), that should still work
