### ISSUE TITLE
CSS Loader for Windows Steam Big Picture Mode?

### ISSUE THREAD

**Issue by akmalamni** [suchmememanyskill/SDH-CssLoader#80]
May I know if there's a way to have the CSSLoader changes for Steam Big Picture Mode in Windows?

**Comment by EMERALD0874** [comment]
Invalid issue, this is already a thing: https://github.com/suchmememanyskill/SDH-CssLoader/releases/tag/v1.6.0

**Comment by suchmememanyskill** [comment]
Probably want to link instructions for how to use it too: https://www.patreon.com/posts/windows-preview-82152788

**Comment by akmalamni** [comment]
> Probably want to link instructions for how to use it too: https://www.patreon.com/posts/windows-preview-82152788

Thanks for this! Looking forward to try this out, really loving the CSSLoader on my SteamDeck!
