### ISSUE TITLE
When a setting/patch is selected, the gray hover element is unusually placed

### ISSUE THREAD

**Issue by vrman123** [suchmememanyskill/SDH-CssLoader#9]
Normally covers entire menu
![Normal](https://user-images.githubusercontent.com/48649272/180440443-09698740-e648-41e8-b142-5aefa3c6ea66.png)

But these only cover a small section. may be intentional, but it doesn't look great.
![setting](https://user-images.githubusercontent.com/48649272/180440562-71339103-bfba-4485-8969-e7557fbf3e07.png)
t

**Comment by beebls** [comment]
I fixed this in PR #10, and once that is merged, it will be in the official version.

**Comment by suchmememanyskill** [comment]
Fixed in release v1.0

**Comment by vrman123** [comment]
This has not been fixed.
The fix only applies to the first patch in a list, as shown here
<img width="1440" alt="Screenshot_2022-07-26_at_16 33 38" src="https://user-images.githubusercontent.com/48649272/181049315-d0f16e46-7d30-44fa-a329-c8facd8d915b.png">
<img width="1440" alt="Screenshot_2022-07-26_at_16 33 44" src="https://user-images.githubusercontent.com/48649272/181049321-e04b9b14-71ab-4f17-8937-a1b3fbe6f662.png">

(The fact that the text goes over two lines is not related to this issue)

**Comment by suchmememanyskill** [comment]
How tf does that even happen lmao

**Comment by beebls** [comment]
Oopsie 😳😳

I (hopefully, as I don't have any theme with multiple patches to test it) fixed it in PR #11
